### ISSUE TITLE
Customize split keys

### ISSUE THREAD

**Issue by levouh** [toppair/reach.nvim#11]
Right now it appears that things like `|`, `-`, etc. are all hard-coded:

```lua
local split_commands = {
  ['|'] = 'vertical sbuffer',
  ['-'] = 'sbuffer',
  [']'] = 'tab sbuffer',
}
```

and private. It would be nice to be able to set something up like `<C-v>` to vertically split a window to be more aligned with the way I have other keymaps setup in my config.

Is something like this possible?

**Comment by toppair** [comment]
Possible now, use it like so:
```lua
require('reach').buffers({
  actions = {
    vertsplit = '<C-V>',
    -- split = ..
    -- tabsplit = ..
    -- delete = ..
    -- priority = ..
  }
})
```
Note the casing, it's sensitive.
