### ISSUE TITLE
`keytrans` keycodes might not match user keycodes

### ISSUE THREAD

**Issue by levouh** [toppair/reach.nvim#13]
Thanks for the additions on #11!

The intention of this issue is to report something else, but just FYI on that feature it requires that you send keycodes as they are returned by `vim.fn.keytrans` - e.g. `<C-v>` does not work, but `<C-V>` does. Not sure if there is something that can be done with the `vim.tbl_contains` to convert values to lowercase without messing up other things, but that might be a good way to allow users to specify keycodes however they like.

**Comment by toppair** [comment]
Both `<C-V>` and `<C-v>` should work now.
