### ISSUE TITLE
Error when starting reach when .cache/nvim does not exist

### ISSUE THREAD

**Issue by Nacho114** [toppair/reach.nvim#16]
Hi,

When doing a setup on a clean machine I got an error (see bellow); I suspect it was not able to create `reach_cache` since the folder `.cache/nvim` did not exist. (I fixed it by creating the `.cache/nvim` folder.

Is this expected behavior? Or should it create the cache nvim folder if it does not exist? (Happy to give a hand!)

This is the error that occurs:

```bash
Error detected while processing /Users/nacho/.config/nvim/init.vim:
line  216:
E5108: Error executing lua Vim:E482: Can't open file /Users/nacho/.cache/nvim/reach_cache for writing: no such file or directory
stack traceback:
        [C]: in function 'writefile'
        ...acho/.config/nvim/plugged/reach.nvim/lua/reach/cache.lua:46: in function 'read_cache'
        ...acho/.config/nvim/plugged/reach.nvim/lua/reach/cache.lua:74: in function 'load'
        ...acho/.config/nvim/plugged/reach.nvim/lua/reach/cache.lua:63: in function 'setup'
        ...nacho/.config/nvim/plugged/reach.nvim/lua/reach/init.lua:28: in function 'setup'
        /Users/nacho/.config/nvim/lua/init.lua:1: in main chunk
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue

```

**Comment by toppair** [comment]
I don't think that directory should be created by a plugin. Are you sure you didn't somehow remove it yourself after you had installed nvim?

Can you run `nvim --version`?

**Comment by Nacho114** [comment]
NVIM v0.8.1; this happened on WSL2 with Ubuntu on it, it was a clean install, pretty sure I didn't remove it.

I removed it later to see if that was indeed why it was complaining. Maybe you are right in that the plug in should not create it, and I guess usually the folder will already exist anyway, maybe this is a bit of a corner case situation, not sure what the best approach is in this case.

**Comment by toppair** [comment]
> maybe this is a bit of a corner case situation

We'll leave it at that. The directory should be there and if it isn't, it's not an issue for a plugin to fix.
