### ISSUE TITLE
Global configuration with optional override in functions

### ISSUE THREAD

**Issue by mhogeveen** [toppair/reach.nvim#17]
A global configuration table passed into the .setup method. For example (pseudo code):

```lua
require('reach').setup({
  global = {
    ...
  },
  buffers = {
    ...
  },
  marks = {
    ...
  },
  colorschemes = {
    ...
  },
  tabpages = {
    ...
  },
})
```

The functions used to open the pickers would then use the above configuration as a default except when additional options were given as parameters. For example:

```lua
require('reach').buffers({ show_current = false })
```

**Comment by toppair** [comment]
I don't see value in that. Users can store options in a variable, modify and extend them as they wish.
```lua
local options = {}
require('reach').buffers(vim.tbl_extend('force', options, { show_current = false }))
```
Why would anyone need to set options via `setup` function?
